package com.foodservice.inventory.gui;
import com.foodservice.inventory.model.InventoryItem; import javax.swing.*; import java.awt.*; import java.time.*; import java.time.format.DateTimeParseException;
public class ItemDialog extends JDialog {
  private final JTextField name=new JTextField(18),supplier=new JTextField(18),price=new JTextField("0.00",18),expiration=new JTextField(18); private final JComboBox<String> category=new JComboBox<>(new String[]{"Produce","Meat","Dairy","Dry Goods","Frozen","Beverage","Cleaning","Other"}),unit=new JComboBox<>(new String[]{"Each","Box","Case","Bag","Pound","Ounce","Gallon","Liter"}); private final JSpinner qty=new JSpinner(new SpinnerNumberModel(0,0,100000,1)),minimum=new JSpinner(new SpinnerNumberModel(5,0,100000,1)); private InventoryItem result;
  public ItemDialog(Frame owner,InventoryItem existing){super(owner,existing==null?"Add Item":"Edit Item",true);setLayout(new BorderLayout());JPanel f=new JPanel(new GridLayout(8,2,8,8));f.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));add(f,BorderLayout.CENTER);addRow(f,"Item name",name);addRow(f,"Category",category);addRow(f,"Quantity",qty);addRow(f,"Unit",unit);addRow(f,"Supplier",supplier);addRow(f,"Unit price",price);addRow(f,"Expiration YYYY-MM-DD",expiration);addRow(f,"Minimum stock",minimum);JButton save=new JButton("Save"),cancel=new JButton("Cancel");JPanel b=new JPanel();b.add(cancel);b.add(save);add(b,BorderLayout.SOUTH);cancel.addActionListener(e->dispose());save.addActionListener(e->save());if(existing!=null){result=new InventoryItem();result.setId(existing.getId());name.setText(existing.getName());category.setSelectedItem(existing.getCategory());qty.setValue(existing.getQuantity());unit.setSelectedItem(existing.getUnit());supplier.setText(existing.getSupplier());price.setText(String.valueOf(existing.getUnitPrice()));expiration.setText(existing.getExpirationDate());minimum.setValue(existing.getMinimumStock());}pack();setLocationRelativeTo(owner);}
  private void addRow(JPanel p,String label,Component c){p.add(new JLabel(label+":"));p.add(c);} public InventoryItem getResult(){return result;}
  private void save(){try{String n=name.getText().trim(),d=expiration.getText().trim();double pr=Double.parseDouble(price.getText().trim());if(n.isBlank())throw new IllegalArgumentException("Item name is required.");if(pr<0)throw new IllegalArgumentException("Price cannot be negative.");if(!d.isBlank())LocalDate.parse(d);if(result==null)result=new InventoryItem();result.setName(n);result.setCategory((String)category.getSelectedItem());result.setQuantity((Integer)qty.getValue());result.setUnit((String)unit.getSelectedItem());result.setSupplier(supplier.getText().trim());result.setUnitPrice(pr);result.setExpirationDate(d);result.setMinimumStock((Integer)minimum.getValue());dispose();}catch(NumberFormatException e){error("Enter a valid price.");}catch(DateTimeParseException e){error("Use YYYY-MM-DD for the expiration date.");}catch(IllegalArgumentException e){error(e.getMessage());}}
  private void error(String m){JOptionPane.showMessageDialog(this,m,"Invalid Information",JOptionPane.ERROR_MESSAGE);}
}
