package com.foodservice.inventory.gui;
import com.foodservice.inventory.dao.InventoryDAO; import com.foodservice.inventory.model.InventoryItem; import javax.swing.*; import javax.swing.event.*; import java.awt.*; import java.util.List;
public class MainFrame extends JFrame {
  private final InventoryDAO dao=new InventoryDAO(); private final InventoryTableModel model=new InventoryTableModel(); private final JTable table=new JTable(model); private final JTextField search=new JTextField(20); private final JCheckBox low=new JCheckBox("Low-stock only"); private final JLabel summary=new JLabel(" ");
  public MainFrame(){super("Food Service Inventory Management System");setDefaultCloseOperation(EXIT_ON_CLOSE);setSize(1100,600);setLocationRelativeTo(null);JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT));top.add(new JLabel("Search:"));top.add(search);top.add(low);add(top,BorderLayout.NORTH);table.setAutoCreateRowSorter(true);table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);add(new JScrollPane(table),BorderLayout.CENTER);JButton add=new JButton("Add"),edit=new JButton("Edit"),delete=new JButton("Delete"),refresh=new JButton("Refresh");JPanel bottom=new JPanel(new BorderLayout());JPanel buttons=new JPanel();buttons.add(add);buttons.add(edit);buttons.add(delete);buttons.add(refresh);bottom.add(buttons,BorderLayout.WEST);bottom.add(summary,BorderLayout.EAST);add(bottom,BorderLayout.SOUTH);DocumentListener dl=new DocumentListener(){public void insertUpdate(DocumentEvent e){load();}public void removeUpdate(DocumentEvent e){load();}public void changedUpdate(DocumentEvent e){load();}};search.getDocument().addDocumentListener(dl);low.addActionListener(e->load());refresh.addActionListener(e->load());add.addActionListener(e->addItem());edit.addActionListener(e->editItem());delete.addActionListener(e->deleteItem());load();}
  private void load(){try{List<InventoryItem> items=dao.findAll(search.getText(),low.isSelected());model.setItems(items);long lowCount=items.stream().filter(InventoryItem::isLowStock).count();double value=items.stream().mapToDouble(InventoryItem::getInventoryValue).sum();summary.setText("Items: "+items.size()+" | Low stock: "+lowCount+" | Value: "+String.format("$%.2f",value));}catch(RuntimeException e){error(e.getMessage());}}
  private InventoryItem selected(){int r=table.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Select an item first.");return null;}return model.getItemAt(table.convertRowIndexToModel(r));}
  private void addItem(){ItemDialog d=new ItemDialog(this,null);d.setVisible(true);if(d.getResult()!=null){dao.insert(d.getResult());load();}}
  private void editItem(){InventoryItem i=selected();if(i==null)return;ItemDialog d=new ItemDialog(this,i);d.setVisible(true);if(d.getResult()!=null){dao.update(d.getResult());load();}}
  private void deleteItem(){InventoryItem i=selected();if(i==null)return;if(JOptionPane.showConfirmDialog(this,"Delete "+i.getName()+"?","Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){dao.delete(i.getId());load();}}
  private void error(String m){JOptionPane.showMessageDialog(this,m,"Error",JOptionPane.ERROR_MESSAGE);}
}
